name:          FE Code Guide for HNA
description:   Standards for developing flexible, durable, and sustainable HTML and CSS, and maintainable JavaScript
url:           http://scottwang.me/code-guide/

markdown:      rdiscount
permalink:     pretty
pygments:      true
highlighter:   rouge

twitterid:	   wyuleo
