name:          FE Code Guide for eKing
description:   Standards for developing flexible, durable, and sustainable HTML and CSS, and maintainable JavaScript
url:           http://wangyu.in/code-guide/

markdown:      rdiscount
permalink:     pretty
pygments:      true

twitterid:	   wyuleo